### ISSUE TITLE
Action Handler 

### ISSUE THREAD

**Issue by nagkumar** [thefrontside/emberx-file-input#22]
How to handle the file which is chosen is not known, pl. provide sample which could push the file selected to server

**Comment by Robdel12** [comment]
I'm going to close this since we've neglected it for a while :/ 

You can look at Charles blog post about functional templating. emberx-file-input is just one component of many needed to create an upload workflow. http://frontside.io/blog/2016/01/22/functional-templating-in-ember.html

Let me know if you have any questions. I promise I won't wait months to reply :(
